apiVersion: v1
kind: ConfigMap # trigger redeploy 
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello World</title>
    </head>
    <body>
      <h1>Hello World</h1>
      <p>Deployed on k3s Kubernetes</p>
    </body>
    </html>

